name: Fabric CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04  # 👈 Changed this line

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install notebook tools
      run: |
        pip install nbconvert jupyter

    - name: Run Silver Notebook
      run: |
        jupyter nbconvert --execute "Notebook Transformations/New Notebooks/Silver_Notebook.ipynb" --to notebook --stdout

    - name: Run Gold Notebook
      run: |
        jupyter nbconvert --execute "Notebook Transformations/New Notebooks/Gold_Notebook.ipynb" --to notebook --stdout
